### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by YilanWang** [Megvii-BaseDetection/cvpods#1]
I have install these requried packages, like cuda10.1,cudnn7.6.3...etc. The final errors are like:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 149, in <module>
    "tools/pods_debug",
  File "/home/wyl/anaconda3/envs/CenterNet/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/wyl/anaconda3/envs/CenterNet/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
    _build_ext.run(self)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
    build_ext.build_extensions(self)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/wyl/anaconda3/envs/CenterNet/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1140, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1413, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
```

and some failures and errors are like：

<details>
FAILED: /home/wyl/PycharmProjects/cvpods/build/temp.linux-x86_64-3.6/home/wyl/PycharmProjects/cvpods/cvpods/layers/csrc/ROIAlignRotated/ROIAlignRotated_cuda.o 
/usr/include/c++/7/bits/basic_string.h:6693:95:   required from here
/usr/include/c++/7/bits/basic_string.tcc:1067:16: error: cannot call member function ‘void std::basic_string<_CharT, _Traits, _Alloc>::_Rep::_M_set_sharable() [with _CharT = char32_t; _Traits = std::char_traits<char32_t>; _Alloc = std::allocator<char32_t>]’ without object
[10/11] /usr/local/cuda-10.1/bin/nvcc -DWITH_CUDA -I/home/wyl/PycharmProjects/cvpods/cvpods/layers/csrc -I/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/include -I/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/include/TH -I/home/wyl/anaconda3/envs/as/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-10.1/include -I/home/wyl/anaconda3/envs/as/include/python3.6m -c -c /home/wyl/PycharmProjects/cvpods/cvpods/layers/csrc/deformable/deform_conv_cuda.cu -o /home/wyl/PycharmProjects/cvpods/build/temp.linux-x86_64-3.6/home/wyl/PycharmProjects/cvpods/cvpods/layers/csrc/deformable/deform_conv_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
FAILED: /home/wyl/PycharmProjects/cvpods/build/temp.linux-x86_64-3.6/home/wyl/PycharmProjects/cvpods/cvpods/layers/csrc/deformable/deform_conv_cuda.o 

</details>

BTW,fg, where is the **requirements.txt**?

**Comment by poodarchu** [comment]
did you build cvpods with GPU?

**Comment by YilanWang** [comment]
> did you build cvpods with GPU?

I found the reason, cvpods cannot build in conda env, it's so weird...I will close this issue but maybe somebody esle should check this~

**Comment by zaidao2023** [comment]
Is this problem solved now?

**Comment by xiexu0210** [comment]
> did you build cvpods with GPU?

hi,I also have the same problem.  Could you give me some advise. 
thank you.
