### ISSUE TITLE
The support for RTX3090?

### ISSUE THREAD

**Issue by caiduoduo12138** [Megvii-BaseDetection/cvpods#4]
when I compile border_align, it seems to work well.  I create a file called test.py to make sure if it works. But error occours,  as shown below：
Traceback (most recent call last):
  File "/home/cai/project/cvpods/test_align.py", line 1, in <module>
    from cvpods.layers.border_align import BorderAlign
  File "/home/cai/project/cvpods/cvpods/__init__.py", line 3, in <module>
    from .utils import setup_environment
  File "/home/cai/project/cvpods/cvpods/utils/__init__.py", line 27, in <module>
    from .visualizer import ColorMode, VideoVisualizer, VisImage, Visualizer, colormap, random_color
  File "/home/cai/project/cvpods/cvpods/utils/visualizer/__init__.py", line 5, in <module>
    from .video_visualizer import *
  File "/home/cai/project/cvpods/cvpods/utils/visualizer/video_visualizer.py", line 6, in <module>
    from .visualizer import ColorMode, Visualizer, _create_text_labels, _PanopticPrediction
  File "/home/cai/project/cvpods/cvpods/utils/visualizer/visualizer.py", line 17, in <module>
    from cvpods.structures import BitMasks, Boxes, BoxMode, Keypoints, PolygonMasks, RotatedBoxes
  File "/home/cai/project/cvpods/cvpods/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_ioa, pairwise_iou
  File "/home/cai/project/cvpods/cvpods/structures/boxes.py", line 11, in <module>
    from cvpods.layers import cat
  File "/home/cai/project/cvpods/cvpods/layers/__init__.py", line 4, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/cai/project/cvpods/cvpods/layers/deform_conv.py", line 11, in <module>
    from cvpods import _C
ImportError: /home/cai/project/cvpods/cvpods/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6cvpods26psroi_pooling_forward_cudaERN2at6TensorES2_S2_iifii
My test.py is test on RTX2080Ti ,it works well. So, I think it is caused by CUDA, however Pytorch does not support CUDA 11.1.  Could you give me some  solutions. Thanks for your great work.

**Comment by poodarchu** [comment]
You need to recompile cvpods on RTX 3090

**Comment by caiduoduo12138** [comment]
I  compiled cvpods on RTX 3090 with torch1.7 or nightly, cuda11.1, Maybe the compute_86  causes the probelm. MMdetection employ 'MMCV_WITH_OPS=1 MMCV_CUDA_ARGS='-gencode=arch=compute_80,code=sm_80' pip install -e' to slove this issue. This solution replace ‘compute_86’ by 'compute_80' which is supported by torch released.

**Comment by poodarchu** [comment]
We haven't test cvpods neither on torch 1.7 or the newest GPU devices. 

However, you can check this https://github.com/pytorch/pytorch/issues/45021 for the pytorch support on 3080/3090.
