### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by xiexu0210** [Megvii-BaseDetection/cvpods#55]
hi, I have problem in  your code.
could you give me some advice.  

 During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/DATA/xiexu/cvpods/setup.py", line 151, in <module>
        "tools/pods_debug",
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/setuptools/command/develop.py", line 136, in install_for_development
        self.run_command('build_ext')
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/xiexu/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
        build_ext.build_extensions(self)
      File "/home/xiexu/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/distutils/command/build_ext.py", line 533, in build_extension
        depends=ext.depends)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
        raise RuntimeError(message)
    RuntimeError: Error compiling objects for extension

**Comment by CatbossMr** [comment]
Hi  you may change the "['ninja','-v']" in "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/torch/utils/cpp_extension.py"  into "['ninja','--version']". This maybe helpful

**Comment by CatbossMr** [comment]
Hi  you may change the "['ninja','-v']" in "/home/xiexu/anaconda3/envs/Bord/lib/python3.7/site-packages/torch/utils/cpp_extension.py"  into "['ninja','--version']". This may be helpful

**Comment by baymingzx** [comment]
hello ,i can not find DisAlignLinear in cvpods.layers .

**Comment by tonysy** [comment]
@baymingzx  Sorry for the inconvenience, the support of DisAlignLinear is under the code review process #62 . We believe this PR will be merged this weekend. You can use this branch https://github.com/tonysy/cvpods/tree/disalign_cls as a temporary solution.

**Comment by JadeKim042386** [comment]
I have the same problem.
