### ISSUE TITLE
No module named lvis

### ISSUE THREAD

**Issue by kuazhangxiaoai** [Megvii-BaseDetection/cvpods#73]
`Traceback (most recent call last):
  File "/home/yanggang/pyworks/code/cvpods/tools/train_net.py", line 23, in <module>
    from cvpods.engine import RUNNERS, default_argument_parser, default_setup, hooks, launch
  File "/home/yanggang/pyworks/code/cvpods/cvpods/engine/__init__.py", line 3, in <module>
    from .hooks import *
  File "/home/yanggang/pyworks/code/cvpods/cvpods/engine/hooks.py", line 15, in <module>
    from cvpods.evaluation.testing import flatten_results_dict
  File "/home/yanggang/pyworks/code/cvpods/cvpods/evaluation/__init__.py", line 15, in <module>
    from .lvis_evaluation import LVISEvaluator
  File "/home/yanggang/pyworks/code/cvpods/cvpods/evaluation/lvis_evaluation.py", line 12, in <module>
    from lvis import LVISEval, LVISResults
ModuleNotFoundError: No module named 'lvis'
`

**Comment by FateScript** [comment]
got it, please use `pip install lvis`, We will fix it later.
