### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by andrew-begain** [Megvii-BaseDetection/cvpods#78]
Running setup.py develop for cvpods
    ERROR: Command errored out with exit status 1:
     command: /home/anaconda3/envs/OTA/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/thomas/cvpods/setup.py'"'"'; __file__='"'"'/home/thomas/cvpods/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/thomas/cvpods/
    Complete output (50 lines):
    which: no hipcc in (/home/anaconda3/envs/OTA/bin:/home/anaconda3/bin:/home/anaconda3/bin:/home/anaconda3/bin:/home/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
    running develop
    running egg_info
    writing cvpods.egg-info/PKG-INFO
    writing dependency_links to cvpods.egg-info/dependency_links.txt
    writing requirements to cvpods.egg-info/requires.txt
    writing top-level names to cvpods.egg-info/top_level.txt
    reading manifest file 'cvpods.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'cvpods.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/thomas/cvpods/setup.py", line 192, in <module>
        "tools/pods_debug",
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/anaconda3/envs/OTA/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/anaconda3/envs/OTA/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/anaconda3/envs/OTA/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/home/anaconda3/envs/OTA/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/anaconda3/envs/OTA/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/root/.local/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/home/anaconda3/envs/OTA/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 308, in build_extensions
        self._check_abi()
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 607, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 215, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/anaconda3/envs/OTA/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 191, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/anaconda3/envs/OTA/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/home/anaconda3/envs/OTA/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/anaconda3/envs/OTA/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/thomas/cvpods/setup.py'"'"'; __file__='"'"'/home/thomas/cvpods/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

@tbfly @zengarden @ruinmessi @tonysy @poodarchu 麻烦问下安装cvpods需要什么环境呢？我试了好几个版本的torch和python都是这个问题，劳烦大佬赐教

**Comment by loading376** [comment]
大佬，安装问题解决了吗

**Comment by FateScript** [comment]
@andrew-begain plz check your gcc version

**Comment by SihangXie** [comment]
> @andrew-begain plz check your gcc version

Hi! Could you please tell me which gcc version is OK?
