### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by PanffeeReal** [Megvii-BaseDetection/cvpods#93]
I did installation guided by this webpage and successfully installed cvpods. 
After that I tried to train a detector like retinanet but meet a file problem :
log is here:
(pytorch) lpf@lpf-AW17:~/cvpods/playground/detection/coco/retinanet/retinanet.res50.fpn.coco.multiscale.1x$ ****pods_train --num-gpus 8****
Traceback (most recent call last):
  File "/home/lpf/cvpods/tools/train_net.py", line 151, in <module>
    from config import config
ModuleNotFoundError: **No module named 'config'**

What happeded ? I am very confused about that because this comes out without any proper reaseon, could you please help me ?thank you very much!!

**Comment by liuhaolinwen** [comment]
i have same， do you solve it？

**Comment by dream1001** [comment]
i have same， do you solve it？

**Comment by dream1001** [comment]
> i have same， do you solve it？

please ask to you had slove it?

**Comment by poodarchu** [comment]
does your working directory contain a config.py?

**Comment by ksv87** [comment]
```
diff --git a/tools/train_net.py b/tools/train_net.py
index 589ba78..c3eef73 100644
--- a/tools/train_net.py
+++ b/tools/train_net.py
@@ -149,7 +149,7 @@ if __name__ == "__main__":
     if args.num_gpus is None:
         args.num_gpus = torch.cuda.device_count()

-    extra_sys_path = ".." if args.dir is None else args.dir
+    extra_sys_path = "." if args.dir is None else args.dir
     sys.path.append(extra_sys_path)

     from config import config
```

**Comment by huxinkai** [comment]
> I did installation guided by this webpage and successfully installed cvpods. After that I tried to train a detector like retinanet but meet a file problem : log is here: (pytorch) lpf@lpf-AW17:~/cvpods/playground/detection/coco/retinanet/retinanet.res50.fpn.coco.multiscale.1x$ **pods_train --num-gpus 8** Traceback (most recent call last): File "/home/lpf/cvpods/tools/train_net.py", line 151, in from config import config ModuleNotFoundError: **No module named 'config'**
> 
> What happeded ? I am very confused about that because this comes out without any proper reaseon, could you please help me ?thank you very much!!

我也遇到了同样的问题，请问你解决了吗？

**Comment by huxinkai** [comment]
> i have same， do you solve it？

我也遇到了同样的问题，请问你解决了吗？

**Comment by huxinkai** [comment]
> > i have same， do you solve it？
> 
> please ask to you had slove it?

我也遇到了同样的问题，请问你解决了吗？
